[package]
name = "parse-video-id"
version = "0.3.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
